[package]
authors = ["Waleed Khan <me@waleedkhan.name>"]
edition = "2018"
name = "git-branchless"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]
name = "branchlessrust"

[dependencies]
anyhow = "1.0.38"
console = "0.14.0"
git2 = "0.13.15"
pyo3 = "0.13.1"
rusqlite = "0.24.2"

[dev-dependencies]
clippy = "0.0.302"

[features]
# See https://pyo3.rs/v0.13.0/faq.html?highlight=test#i-cant-run-cargo-test-im-having-linker-issues-like-symbol-not-found-or-undefined-reference-to-_pyexc_systemerror
# Must run `cargo test --no-default-features` to get tests to run.
# Can remove this once PyO3 is not longer a dependency.
default = ["extension-module"]
extension-module = ["pyo3/extension-module"]
