[package]
authors = ["Waleed Khan <me@waleedkhan.name>"]
categories = ["command-line-utilities", "development-tools"]
description = "Branchless workflow for Git"
documentation = "https://github.com/arxanas/git-branchless/wiki"
edition = "2018"
homepage = "https://github.com/arxanas/git-branchless"
keywords = ["cli", "git"]
license = "Apache-2.0"
name = "git-branchless"
repository = "https://github.com/arxanas/git-branchless"
version = "0.3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "branchless"

[dependencies]
anyhow = "1.0.38"
assert_cmd = "1.0.3"
console = "0.14.0"
cursive = {version = "0.16.3", features = ["crossterm-backend"]}
fn-error-context = "0.1.1"
git2 = {version = "0.13.17", default-features = false}
lazy_static = "1.4.0"
log = "0.4.14"
regex = "1.4.4"
rusqlite = "0.24.2"
simple_logger = "1.11.0"
structopt = "0.3.21"
tempfile = "3.2.0"

[dev-dependencies]
clippy = "0.0.302"
insta = "1.7.0"
