name: Bug report
description: Create a report to help us improve
labels:
- bug

body:
- type: markdown
  value: |
    Thanks for reporting a bug! This form is for bugs which can be resolved with a concrete solution. To ask a question or to brainstorm solutions to a problem, start a [Discussion](https://github.com/arxanas/git-branchless/discussions) instead.

- type: textarea
  id: description
  attributes:
    label: Description of the bug
    description: Include a description of the bug and steps to reproduce the issue.
  validations:
    required: true

- type: textarea
  id: expected-behavior
  attributes:
    label: Expected behavior
    description: What did you expect to happen?

- type: textarea
  id: actual-behavior
  attributes:
    label: Actual behavior
    description: What actually happened?

- type: input
  id: git-branchless-version
  attributes:
    label: Version of `git-branchless`
    description: Paste the output of `git branchless --version` here.
    placeholder: "Example: git-branchless 0.3.7"
  validations:
    required: true
  
- type: input
  id: rustc-version
  attributes:
    label: Version of `rustc`
    description: If this is a build issue, paste the output of `rustc --version` here.
    placeholder: "Example: rustc 1.55.0 (c8dfcfe04 2021-09-06)"
